spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwer

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mysecretkeymysecretkey
  expiration:
    ms: 86400000

lombok:
  accessors:
    chain: true
    fluent: true
